//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string adminHeader {
            get {
                return ResourceManager.GetString("adminHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iZine Publish - Working Apart Together.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string appname {
            get {
                return ResourceManager.GetString("appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archief.
        /// </summary>
        internal static string arhieveHeader {
            get {
                return ResourceManager.GetString("arhieveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Name.
        /// </summary>
        internal static string assetname {
            get {
                return ResourceManager.GetString("assetname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annuleren.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified PDF.
        /// </summary>
        internal static string certifiedPdfHeader {
            get {
                return ResourceManager.GetString("certifiedPdfHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binnenkort beschikbaar.
        /// </summary>
        internal static string comingSoon {
            get {
                return ResourceManager.GetString("comingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date in the format dd-mm-yyyy.
        /// </summary>
        internal static string dateFormatInfo {
            get {
                return ResourceManager.GetString("dateFormatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verwijderen.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u wilt verwijderen van dit object?.
        /// </summary>
        internal static string deleteConfirmation {
            get {
                return ResourceManager.GetString("deleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        internal static string documentname {
            get {
                return ResourceManager.GetString("documentname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string DownloadsHeader {
            get {
                return ResourceManager.GetString("DownloadsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bewerken.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editie.
        /// </summary>
        internal static string edition {
            get {
                return ResourceManager.GetString("edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edities.
        /// </summary>
        internal static string editionHeader {
            get {
                return ResourceManager.GetString("editionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailadres.
        /// </summary>
        internal static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail instellingen.
        /// </summary>
        internal static string emailSettings {
            get {
                return ResourceManager.GetString("emailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to van.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to van is required.
        /// </summary>
        internal static string fromDaterequired {
            get {
                return ResourceManager.GetString("fromDaterequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string homeHeader {
            get {
                return ResourceManager.GetString("homeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockedout.
        /// </summary>
        internal static string lockedOut {
            get {
                return ResourceManager.GetString("lockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginHeader {
            get {
                return ResourceManager.GetString("loginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middlename.
        /// </summary>
        internal static string middleName {
            get {
                return ResourceManager.GetString("middleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam is niet ingevuld.
        /// </summary>
        internal static string nameNotCompleted {
            get {
                return ResourceManager.GetString("nameNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIEUW.
        /// </summary>
        internal static string newBtn {
            get {
                return ResourceManager.GetString("newBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisatie.
        /// </summary>
        internal static string organisation {
            get {
                return ResourceManager.GetString("organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisaties.
        /// </summary>
        internal static string organisationHeader {
            get {
                return ResourceManager.GetString("organisationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemeen.
        /// </summary>
        internal static string overAll {
            get {
                return ResourceManager.GetString("overAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina.
        /// </summary>
        internal static string pageNumber {
            get {
                return ResourceManager.GetString("pageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        internal static string Passwordlbl {
            get {
                return ResourceManager.GetString("Passwordlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicatie.
        /// </summary>
        internal static string publication {
            get {
                return ResourceManager.GetString("publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicatie overzicht.
        /// </summary>
        internal static string publicationHeader {
            get {
                return ResourceManager.GetString("publicationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaaa.
        /// </summary>
        internal static string refreshButtonImg {
            get {
                return ResourceManager.GetString("refreshButtonImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken op.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selecteer een editie.
        /// </summary>
        internal static string selectEdition {
            get {
                return ResourceManager.GetString("selectEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer bestand te uploaden.
        /// </summary>
        internal static string selectFileToUpload {
            get {
                return ResourceManager.GetString("selectFileToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selecteer een Organisatie.
        /// </summary>
        internal static string selectOrganisation {
            get {
                return ResourceManager.GetString("selectOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selecteer een titel.
        /// </summary>
        internal static string selectTitle {
            get {
                return ResourceManager.GetString("selectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select title.
        /// </summary>
        internal static string selectTtitleErr {
            get {
                return ResourceManager.GetString("selectTtitleErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status overzicht.
        /// </summary>
        internal static string statusHeading {
            get {
                return ResourceManager.GetString("statusHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderwerp.
        /// </summary>
        internal static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        internal static string surName {
            get {
                return ResourceManager.GetString("surName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to titel.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titels.
        /// </summary>
        internal static string titleHeader {
            get {
                return ResourceManager.GetString("titleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titels.
        /// </summary>
        internal static string titles {
            get {
                return ResourceManager.GetString("titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tot.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tot is required.
        /// </summary>
        internal static string toDaterequired {
            get {
                return ResourceManager.GetString("toDaterequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Asset.
        /// </summary>
        internal static string unlockasset {
            get {
                return ResourceManager.GetString("unlockasset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u wilt ontgrendelen dit object?.
        /// </summary>
        internal static string unlockconfirmation {
            get {
                return ResourceManager.GetString("unlockconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ontsluiten.
        /// </summary>
        internal static string unlockHeader {
            get {
                return ResourceManager.GetString("unlockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruiker.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikers.
        /// </summary>
        internal static string userHeader {
            get {
                return ResourceManager.GetString("userHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewijzigd door.
        /// </summary>
        internal static string userLastEdited {
            get {
                return ResourceManager.GetString("userLastEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        internal static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        internal static string userNamelbl {
            get {
                return ResourceManager.GetString("userNamelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versie.
        /// </summary>
        internal static string versionNumber {
            get {
                return ResourceManager.GetString("versionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom bij beheerder paneel.
        /// </summary>
        internal static string welcomeAdministratorPanel {
            get {
                return ResourceManager.GetString("welcomeAdministratorPanel", resourceCulture);
            }
        }
    }
}
